# Generated by Django 5.1.1 on 2024-10-03 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='participant_name',
            field=models.CharField(default='Неизвестный участник', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedules.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
